repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
      - id: check-yaml
      - id: sort-simple-yaml
      - id: check-json
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: pretty-format-json
        args: ['--autofix']
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.13.1-1
    hooks:
      - id: shfmt
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        name: shellcheck (scripts)
        exclude: '(^|/)PKGBUILD$'
      - id: shellcheck
        alias: shellcheck-pkgbuild
        name: shellcheck (PKGBUILD)
        files: '(^|/)PKGBUILD$'
        args: ['--rcfile=.shellcheckrc-pkgbuild']
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
        args: ['-shellcheck']
