name: 'Arch Linux User Repository (AUR) GitHub Action'
description: 'Arch Linux User Repository (AUR) GitHub Action'
author: 'JamieMagee'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  pkgname:
    description: 'Package directory name'
    required: true
runs:
  using: docker
  image: docker://aur-builder:latest
