on:
  push:
    branches:
      - main
  pull_request:
name: CI
permissions:
  contents: read
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - name: All files (main)
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0
        with:
          extra-args: '--all-files'
      - name: Changed files (PR)
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0
        with:
          extra-args: >-
            --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
      - uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: .github/actions/aur/Dockerfile
  lint-namcap:
    name: Lint PKGBUILDs (namcap)
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install namcap
        run: pacman -Syu --noconfirm --needed namcap
      - name: Check PKGBUILDs with namcap
        run: .github/scripts/namcap-pkgbuild.sh
